### ISSUE TITLE
Immediate feedback for invalid feed URL

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#11]
It would be great if when a feed is entered on the dashboard it can give immediate feedback as to whether or not there is typo or if a feed can actually be found at the location given - it doesn't have to parse and process, just give a warm fuzzy of a green or red indicator.

**Comment by spurton** [comment]
I have added a green checkbox next to the post count if it is good. A red x and "feed could not be parsed!" if it is not.
