### ISSUE TITLE
Navigation from feed edit screen back to feed

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#19]
When I have edited a feed promotion settings and hit update, there is no way to go back to the specific feed other than browser back button .. when then shows my old settings until I hit a refresh .. I just see help desk tickets here because it confused me :)

Can you have a link to go back to the feed being edited .. so from here: 
http://dashboard.wpsocialexplosion.com/#/rss_feeds/edit/3239
back to here:
http://dashboard.wpsocialexplosion.com/#/rss_feeds/show/3239

**Comment by spurton** [comment]
I am adding a bread-crumbs nav at the top so you can see where you are and go back
