### ISSUE TITLE
Need a new Tab to show people what posts have been promoted

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#2]
Need a subset of the admin functionality for viewing a submitted post in the dashboard so that users can view what's been submitted and promoted and can repromote existing submissions.
http://screencast.com/t/qxbaTBzIn

This should be accompanied with a filter function:
![filter_options](https://cloud.githubusercontent.com/assets/5375039/8363160/80a0302c-1b3a-11e5-80fd-1c7d855e5336.png)

**Comment by spurton** [comment]
Do we want to allow them to reschedule the individual promotions or the entire post?

**Comment by networkempire** [comment]
reschedule the entire post

**Comment by spurton** [comment]
How does this look? https://dl.dropboxusercontent.com/u/6988350/Screen%20Shot%202015-08-19%20at%203.21.53%20PM.png
