### ISSUE TITLE
No indication / edit capability for existing feeds in dashboard

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#3]
On the dashboard I can't see what the settings are for each of my feeds.
could I please have an indicator of what the settings are for each platform, and the ability to modify those settings?

**Comment by spurton** [comment]
I can display the settings they chose, we can't modify it because everything is already scheduled if it is saved.

**Comment by spurton** [comment]
I actually added a note for customers to know when they edit those it is only for future posts.
