### ISSUE TITLE
Name the feeds

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#4]
Can I have the name of the feed right above the appropriate feed url? (name from the xml is fine)

**Comment by spurton** [comment]
Should I allow for a custom name? I can sometimes get the name from the RSS feed that is put into the field. I am thinking of auto-filling the name and let them change it if need be...

**Comment by spurton** [comment]
I added a form field which auto populates it from the RSS feed title but can also be manually added.
