### ISSUE TITLE
Dashboard Add Feed Calculator doesn't work

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#9]
calculator for feed doesn't work:  http://screencast.com/t/jl8enH2CgCyW

**Comment by spurton** [comment]
Maybe the feed wasn't parsable at the time? I can get it to load: https://dl.dropboxusercontent.com/u/6988350/Screen%20Shot%202015-07-13%20at%201.32.13%20PM.png

**Comment by spurton** [comment]
Since I can't reproduce, I am closing this
